# Generated by Django 6.0 on 2025-12-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
